name: Deploy to Ionos

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: |
          sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload Site
        run: |
          lftp -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} sftp://${{ secrets.SFTP_HOST }}:22 -e "mirror --reverse --delete site/ /; exit"

      - name: Cleanup
        run: |
          rm -rf site
